name: Run Result (run.py)

on:
  schedule:
    - cron: "0 */3 * * *" # jalan tiap 3 jam
  workflow_dispatch: # bisa manual run

jobs:
  run-result:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies for Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libxss1 \
            libasound2 \
            libgbm1 \
            libgtk-3-0 \
            libdrm2 \
            libx11-xcb1 \
            libxcb-dri3-0

      - name: Install Python dependencies
        run: |
          pip install requests beautifulsoup4 playwright
          playwright install chromium

      - name: Run run.py
        run: |
          python run.py
