name: Run Result Script

on:
  schedule:
    - cron: "0 */3 * * *" # tiap 3 jam sekali
  workflow_dispatch: # biar bisa manual run

jobs:
  run-result:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 playwright
          playwright install chromium

      - name: Run run.py
        run: |
          python run.py
